modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license="${mod_license}"
issueTrackerURL = "${mod_issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
logoFile = "logo.png"
logoBlur = false
authors = "${mod_authors}"
#credits=""
description='''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type = "required" #mandatory
versionRange = "[${neo_version},)" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "nerb"
type = "incompatible"
reason = "Recipe Book data is required on the client side."
versionRange = ""
ordering = "NONE"
side = "BOTH"
